spring.datasource.url=jdbc:postgresql://localhost:5432/recruta
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

rsa.private_key=classpath:keys/private_key.pem
rsa.public_key=classpath:keys/public_key.pem

token.expiration=1800
token.refresh_expiration=7200

spring.flyway.enabled=true
spring.flyway.create-schemas=true
spring.flyway.schemas=auth
spring.flyway.locations=classpath:db/migration